version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: beatysalon_db
    environment:
      POSTGRES_DB: beatysalon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      backend:
    ports:
      - "5438:5432"
  client:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      db_url: jdbc:postgresql://postgres:5432/beatysalon
      db_username: postgres
      db_password: postgres
    networks:
      backend:
        aliases:
          - "report"
    ports:
      - "8080:8080"
  gateway:
    image: gateway/gateway
    ports:

      - "8082:8082"

    networks:
      backend:
        aliases:
          - "gateway"

networks:
  backend:
    driver: bridge