version: '3.9'
services:
  report:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      db_url: jdbc:postgresql://postgres:5432/beatysalon
      db_username: postgres
      db_password: postgres
    networks:
      backend:
        aliases:
          - "reportService"
    ports:
      - "8081:8081"

networks:
  backend:
    driver: bridge