spring:
  datasource:

    url: jdbc:postgresql://beatysalon_db:5432/beatysalon
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  doc:
    swager-ui:
      enabled: true
      version: 3.1.0
    api-docs:
      version: openapi.3.1
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false