spring:
  datasource:
    url: ${db_url}
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  logging:
    level:
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG

  springdoc:
    api-docs:
      path: /client/v3/api-docs
    swagger-ui:
      path: /client/swagger-ui.html

  openapi:
    service:
      title: client doc
      version: 1.0.0
      url: http://localhost:8080

