server:
  port: 8082

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Применение ко всем маршрутам
            allowedOriginPatterns: "*"      # Разрешить все источники
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
      - id: client
        uri: http://client:8080
        predicates:
          - Path=/client/**, /client/v3/api-docs
        filters:
          - RewritePath=/client/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie, SetCookie
      - id: report
        uri: http://report:8081
        predicates:
          - Path=/report/**, /report/v3/api-docs
        filters:
          - RewritePath=/report/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie, SetCookie
      - id: client_report
        predicates:
          - Path=/client/**
        uri: http://localhost:8082
      - id: reportService
        predicates:
          - Path=/report/**
        uri: http://localhost:8081



springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: gateway-service
        url: /v3/api-docs


      - url: /client/v3/api-docs
        name: client_report

      - url: /report/v3/api-docs
        name: reportService


management:
  endpoints:
    web:
      exposure:
        include: "*"
